name: "Static code analysis"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-code-analysis:
    runs-on: macos-12
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Chackout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .build/artifacts
            .build/checkouts
            .build/repositories
            DevTools/.build/artifacts
            DevTools/.build/checkouts
            DevTools/.build/repositories
          key: ${{ runner.os }}-dependencies-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
            ${{ runner.os }}-dependencies-${{ matrix.xcode }}-
      - name: Install Danger JS
        run: npm install -g danger
      - name: Run Danger
        run: swift run -c=release --package-path=DevTools danger-swift ci --dangerfile=DevTools/Danger/Dangerfile.swift

