name: "Static code analysis"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-code-analysis:
    runs-on: macos-12
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Chackout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .build/artifacts
            .build/checkouts
            .build/repositories
            DevTools/.build/artifacts
            DevTools/.build/checkouts
            DevTools/.build/repositories
          key: ${{ runner.os }}-dependencies-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
            ${{ runner.os }}-dependencies-${{ matrix.xcode }}-
      - name: Install Danger
        run: brew install danger/tap/danger-swift
      - name: Run Danger
        run: cd DevTools && swift run -c release danger-swift ci

